>P1;1fxd
structure:1fxd:FIRST:@:58:@:.:.:.:.
PIEVNDDCMACEACVEICPDVFEMNEEGDKAVVINPDSDLDCVEEAIDSCPAEAIVRS-
*
>P1;1fdn
structure:1fdn:FIRST:@:55:@:.:.:.:.
AYVINEACISCGACEPECP--VNAISSGDDRYVIDADTCIDCGACAG-VCPVDAPVQA-
*
>P1;ferodoxM
sequence:1fdx:1: :55: :ferredoxin:Peptococcus aerogenes: 2.00:-1.00
AYVINDSCIACGACKPECP--VNIIQEGS-IYAIDADSCIDCGSCAS-VCPVGAPNPED
*
