# Rest of ferodoxin family sequences (also have structures in atom_files)

>P1;1clf
structure:1clf:FIRST:@:55   :@:.:.:.:.
AYKIADSCVSCGACASECPVNAISQGDSIFVIDADTCIDCGNCANVCPVGAPVQE*

>P1;1fca
structure:1fca:FIRST:@:55   :@:.:.:.:.
AYVINEACISCGACEPECPVDAISQGGSRYVIDADTCIDCGACAGVCPVDAPVQA*

>P1;2fxb
structure:2fxb:FIRST:@:81   :@:.:.:.:.
PKYTIVDKETCIACGACGAAAPDIYDYDEDGIAYVTLDDNQGIVEVPDILIDDMMDAFEGCPTDSIKVADEPFDGDPNKFE*
